spin_manifest_version = 2

[application]
authors = ["Frederic Leger <frederic@webofmars.com>"]
description = "demo app with spin"
name = "demo"
version = "0.1.0"

[[trigger.http]]
route = "/"
component = "demo"

[component.demo]
source = "app.wasm"
[component.demo.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
